#include "gpio.h"

/** Configure pins as
        * Analog
        * Input
        * Output
        * EVENT_OUT
        * EXTI
*/

void GPIO_Init(void)
{
    /* AS5047P */
    /* SPI2_NSS  PA15 */
    /* SPI2_SCK  PC10 */
    /* SPI2_MISO PC11 */
    /* SPI2_MOSI PC12 */
    gpio_pin_remap_config(GPIO_SPI2_REMAP, ENABLE);
    gpio_pin_remap_config(GPIO_SWJ_SWDPENABLE_REMAP, ENABLE); // nCS/PA15
    gpio_init(GPIOC, GPIO_MODE_AF_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_10 | GPIO_PIN_12);
    gpio_init(GPIOC, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_10MHZ, GPIO_PIN_11);
    gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_15);
    gpio_bit_set(GPIOA, GPIO_PIN_15);

    /* DRV8323RS SPI */ 
    /* SPI1_NSS  PB12 */
    /* SPI1_SCK  PB13 */
    /* SPI1_MISO PB14 */
    /* SPI1_MOSI PB15 */
    gpio_init(GPIOB, GPIO_MODE_AF_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_13 | GPIO_PIN_15);
    gpio_init(GPIOB, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_10MHZ, GPIO_PIN_14);
    gpio_init(GPIOB, GPIO_MODE_OUT_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_12);
    gpio_bit_set(GPIOB, GPIO_PIN_12);

    /* DRV8323RS Enable/nFault */
    /* ENABLE PA11 */
    /* nFAULT PA12 */
    gpio_init(GPIOA, GPIO_MODE_OUT_PP, GPIO_OSPEED_2MHZ, GPIO_PIN_11);
    gpio_init(GPIOA, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_50MHZ, GPIO_PIN_12);
    gpio_bit_reset(GPIOA, GPIO_PIN_11);

    /* DRV8323RS PWM */
    /* TIMER0_CH0 PA8 */
    /* TIMER0_CH1 PA9 */
    /* TIMER0_CH2 PA10 */
    gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_50MHZ, GPIO_PIN_8|GPIO_PIN_9|GPIO_PIN_10);

    /* DRV8323RS Current Sense */
    /* SOC/ADC012_IN10 PC0 */
    /* SOB/ADC012_IN11 PC1 */
    gpio_init(GPIOC, GPIO_MODE_AIN, GPIO_OSPEED_MAX, GPIO_PIN_0|GPIO_PIN_1);

    /* TEMP_PCB/ADC01_IN8     PB0 */
    /* TEMP_MOTOR/ADC012_IN12 PC2 */
    /* VOLT_VBUS/ADC012_IN13  PC3 */
    gpio_init(GPIOB, GPIO_MODE_AIN, GPIO_OSPEED_MAX, GPIO_PIN_0);
    gpio_init(GPIOC, GPIO_MODE_AIN, GPIO_OSPEED_MAX, GPIO_PIN_2|GPIO_PIN_3);

    /* HALL0/ADC01_IN4  PA4 */
    /* HALL1/ADC01_IN5  PA5 */
    /* HALL2/ADC01_IN6  PA6 */
    /* HALL3/ADC01_IN7  PA7 */
    /* HALL4/ADC01_IN14 PC4 */
    /* HALL5/ADC01_IN15 PC5 */
    gpio_init(GPIOA, GPIO_MODE_AIN, GPIO_OSPEED_MAX, GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6|GPIO_PIN_7);
    gpio_init(GPIOC, GPIO_MODE_AIN, GPIO_OSPEED_MAX, GPIO_PIN_4|GPIO_PIN_5);
    
    /* LED PC13 */
    gpio_init(GPIOC, GPIO_MODE_OUT_PP, GPIO_OSPEED_2MHZ, GPIO_PIN_13);

    /* USART1_TX PA2 */
    /* USART1_RX PA3 */
    gpio_init(GPIOA, GPIO_MODE_AF_PP, GPIO_OSPEED_10MHZ, GPIO_PIN_2);
    gpio_init(GPIOA, GPIO_MODE_IN_FLOATING, GPIO_OSPEED_10MHZ, GPIO_PIN_3);

    /* CAN0_RX PB8 */
    /* CAN0_TX PB9 */
    gpio_pin_remap_config(GPIO_CAN_PARTIAL_REMAP, ENABLE);
    gpio_init(GPIOB, GPIO_MODE_IPU, GPIO_OSPEED_2MHZ, GPIO_PIN_8);
    gpio_init(GPIOB, GPIO_MODE_AF_PP, GPIO_OSPEED_2MHZ, GPIO_PIN_9);
}

